### ISSUE TITLE
Not able to monitor events on the Azure CLI

### ISSUE THREAD

**Issue by olivakar** [Azure/azure-iot-cli-extension#269]
## Describe the bug

**Command Name**
`az iot hub monitor-events
Extension Name: azure-cli-iot-ext. Version: 0.7.1.`

**Errors:**
```
Please provide an IoT Hub entity name (via the '--hub-name' or '-n' parameter) or IoT Hub connection string via --login...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Open Azure CLI shell from azure portal
- Make sure correct account and subscription is set.
- `az iot hub monitor-events --hubname checkissue698`

## Expected Behavior

Should be able to monitor events

## Environment Summary
```
Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.14.0 *
azure-cli-iot-ext 0.7.1

Extensions:
azure-cli-iot-ext 0.7.1
ai-examples 0.2.4

```
## Additional Context

The error I got after running the monitor events command
```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
No module named 'azure.mgmt.iothub.iot_hub_client'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/home/oliva/.azure/cliextensions/azure-cli-iot-ext/azext_iot/operations/hub.py", line 1323, in iot_hub_monitor_events
    target = get_iot_hub_connection_string(cmd, hub_name, resource_group_name, include_events=True, login=login)
  File "/home/oliva/.azure/cliextensions/azure-cli-iot-ext/azext_iot/common/_azure.py", line 90, in get_iot_hub_connection_string
    client = iot_hub_service_factory(cmd.cli_ctx)
  File "/home/oliva/.azure/cliextensions/azure-cli-iot-ext/azext_iot/_factory.py", line 29, in iot_hub_service_factory
    from azure.mgmt.iothub.iot_hub_client import IotHubClient
ModuleNotFoundError: No module named 'azure.mgmt.iothub.iot_hub_client'
```

**Comment by digimaun** [comment]
hey @olivakar . Please uninstall the deprecated (soon to be deleted) `azure-cli-iot-ext` and install `azure-iot`. This problem should go away then.

**Comment by olivakar** [comment]
Thanks.
You can close the issue.

**Comment by digimaun** [comment]
@olivakar confirmed the instructions worked.
