### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by aleksve** [Azure/azure-iot-cli-extension#350]
## Describe the bug

**Command Name**
`az iot hub device-identity create
Extension Name: azure-iot. Version: 0.9.7.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'ErrorDetailsException'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/veksler/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 129, in iot_device_create
    hub_name=hub_name, resource_group_name=resource_group_name, login=login
  File "/home/veksler/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 115, in get_target
    target_iothub = self.find_iothub(hub_name=hub_name, rg=rg)
  File "/home/veksler/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 38, in find_iothub
    from azure.mgmt.iothub.models import ErrorDetailsException
ImportError: cannot import name 'ErrorDetailsException'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub device-identity create --hub-name {} --device-id {} --edge-enabled`

## Environment Summary
```
Linux-5.8.0-53-generic-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.24.0

Extensions:
azure-iot 0.9.7

```

**Comment by aleksve** [comment]
@digimaun Thanks, it worked. I also re-installed the Azure CLI by using the instructions [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt).
