### ISSUE TITLE
cli obtaining connection string, fails with internal bug "AttributeError: 'IotHubResourceOperations' object has no attribute 'config'"

### ISSUE THREAD

**Issue by bentheadset** [Azure/azure-iot-cli-extension#380]
## Describe the bug

**Command Name**
`az iot hub connection-string show
Extension Name: azure-iot. Version: 0.10.10.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'IotHubResourceOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 417, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/home/mike/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2663, in iot_hub_connection_string_show
    hub = discovery.find_iothub(hub_name, resource_group_name)
  File "/home/mike/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 72, in find_iothub
    self._initialize_client()
  File "/home/mike/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 35, in _initialize_client
    self.sub_id = self.client.config.subscription_id
AttributeError: 'IotHubResourceOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub connection-string show --hub-name {}`

## Environment Summary
```
Linux-5.8.0-55-generic-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.25.0

Extensions:
azure-iot 0.10.10
resource-graph 2.1.0
application-insights 0.1.13

```
## Additional Context

```
The command failed with an unexpected error. Here is the traceback:
'IotHubResourceOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 417, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/home/mike/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2663, in iot_hub_connection_string_show
    hub = discovery.find_iothub(hub_name, resource_group_name)
  File "/home/mike/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 72, in find_iothub
    self._initialize_client()
  File "/home/mike/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 35, in _initialize_client
    self.sub_id = self.client.config.subscription_id
AttributeError: 'IotHubResourceOperations' object has no attribute 'config'
```

**Comment by bentheadset** [comment]
appears fixed with iot extension upgrade
