### ISSUE TITLE
az iot hub monitor-events -n {} error

### ISSUE THREAD

**Issue by AiHaibara** [Azure/azure-iot-cli-extension#381]
## Describe the bug

**Command Name**
`az iot hub monitor-events
Extension Name: azure-iot. Version: 0.9.7.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'ErrorDetailsException'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/alan_liu/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2265, in iot_hub_monitor_events
    device_query=device_query,
  File "/home/alan_liu/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2350, in _iot_hub_monitor_events
    login=login,
  File "/home/alan_liu/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 115, in get_target
    target_iothub = self.find_iothub(hub_name=hub_name, rg=rg)
  File "/home/alan_liu/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 38, in find_iothub
    from azure.mgmt.iothub.models import ErrorDetailsException
ImportError: cannot import name 'ErrorDetailsException'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub monitor-events -n {}`

## Environment Summary
```
Linux-5.4.0-1051-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.25.0

Extensions:
eventgrid 0.4.9
azure-iot 0.9.7
application-insights 0.1.8
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by c-ryan-k** [comment]
Hey @AiHaibara - this is due to a breaking change in a newer version of the Azure CLI core (you're using `2.25.0`) that's incompatible with our older extension versions.

You'll need to update your `azure-iot` extension to at least `0.10.13` or newer with:
`az extension update --name azure-iot`

**Comment by AiHaibara** [comment]
@c-ryan-k  
`az extension update --name azure-iot`
solved, thanks
