### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by bkatul** [Azure/azure-iot-cli-extension#392]
## Describe the bug

**Command Name**
`az iot device simulate
Extension Name: azure-iot. Version: 0.9.7.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'ErrorDetailsException'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/atul/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2002, in iot_simulate_device
    hub_name=hub_name, resource_group_name=resource_group_name, login=login
  File "/home/atul/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 115, in get_target
    target_iothub = self.find_iothub(hub_name=hub_name, rg=rg)
  File "/home/atul/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 38, in find_iothub
    from azure.mgmt.iothub.models import ErrorDetailsException
ImportError: cannot import name 'ErrorDetailsException'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot device simulate -d {} -n {}`

## Environment Summary
```
Linux-5.4.0-1051-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.26.0 *

Extensions:
azure-iot 0.9.7
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by c-ryan-k** [comment]
Hey @bkatul - this error is caused by using the newest `azure-cli` core with an older version of our extension.

You can update the extension with `az extension update --name azure-iot`

Please re-open this issue if it persists after updating the extension to a version of `0.10.13` or newer
