### ISSUE TITLE
az iot hub generate-sas-token Errors

### ISSUE THREAD

**Issue by sebmaspd** [Azure/azure-iot-cli-extension#399]
## Describe the bug

**Command Name**
`az iot hub generate-sas-token
Extension Name: azure-iot. Version: 0.10.10.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'IotHubResourceOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/ubuntu/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 1647, in iot_get_sas_token
    login,
  File "/home/ubuntu/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 1673, in _iot_build_sas_token
    login=login,
  File "/home/ubuntu/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 136, in get_target
    target_iothub = self.find_iothub(hub_name=hub_name, rg=rg)
  File "/home/ubuntu/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 72, in find_iothub
    self._initialize_client()
  File "/home/ubuntu/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 35, in _initialize_client
    self.sub_id = self.client.config.subscription_id
AttributeError: 'IotHubResourceOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub generate-sas-token -d {} -m {} -n {} --du {}`

## Environment Summary
```
Linux-5.4.0-80-generic-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.26.1

Extensions:
azure-iot 0.10.10

```

**Comment by digimaun** [comment]
@sebmaspd

**Comment by digimaun** [comment]
We are going to close this issue as the recommended resolution (upgrading the `azure-iot` extension) has worked consistently for other users running into the same thing. If it doesn't work for you, you can comment on this issue and we can re-open.
