### ISSUE TITLE
unable to send any command to the device from the cloud

### ISSUE THREAD

**Issue by sathya-gadgeon** [Azure/azure-iot-cli-extension#420]
## Describe the bug

**Command Name**
`az iot device c2d-message send
Extension Name: azure-iot. Version: 0.9.1.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'IotHubResourceOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/sathyanarayanan_a/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 1286, in iot_c2d_message_send
    target = get_iot_hub_connection_string(cmd, hub_name, resource_group_name, login=login)
  File "/home/sathyanarayanan_a/.azure/cliextensions/azure-iot/azext_iot/common/_azure.py", line 158, in get_iot_hub_connection_string
    result['subscription'] = client.config.subscription_id
AttributeError: 'IotHubResourceOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot device c2d-message send -d {} --data {} -n {} --debug`

## Environment Summary
```
Linux-5.4.0-1056-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.27.0 *
azure-cli-iot-ext 0.8.9

Extensions:
azure-iot 0.9.1
azure-cli-iot-ext 0.8.9
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by c-ryan-k** [comment]
@sathya-gadgeon - it looks like you also have the old `azure-cli-iot-ext` version of our extension installed.

To fix this error:
1. Remove the previous extension: `az extension remove --name azure-cli-iot-ext`
2. Update the existing extension to the newest released version: `az extension update --name azure-iot`

I'll close this for now since this is a known issue with a fix - if these steps don't work for you please let us know and we can re-open the issue.
