### ISSUE TITLE
az iot edge commands fail

### ISSUE THREAD

**Issue by YarekTyshchenko** [Azure/azure-iot-cli-extension#423]
## Describe the bug
az iot edge commands fail with the same error message. listing deployments, and set-modules.

Command is executed from CloudShell, so I assume all the dependencies are correctly installed

**Command Name**
`az iot edge set-modules
Extension Name: azure-iot. Version: 0.10.9.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'IotHubResourceOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/yarek/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 970, in iot_edge_set_modules
    hub_name=hub_name, resource_group_name=resource_group_name, login=login
  File "/home/yarek/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 136, in get_target
    target_iothub = self.find_iothub(hub_name=hub_name, rg=rg)
  File "/home/yarek/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 72, in find_iothub
    self._initialize_client()
  File "/home/yarek/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 35, in _initialize_client
    self.sub_id = self.client.config.subscription_id
AttributeError: 'IotHubResourceOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot edge set-modules --device-id {} -n {} --content {}`

## Environment Summary
```
Linux-5.4.0-1056-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.27.0 *

Extensions:
azure-iot 0.10.9
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by YarekTyshchenko** [comment]
/sigh/ Yes, updating the extension fixes the problem. It would be nice if `az upgrade` suggested that, and not just throw an error...
