### ISSUE TITLE
az iot hub device-identity list  -n $HubName faiilure

### ISSUE THREAD

**Issue by djaus2** [Azure/azure-iot-cli-extension#424]
## Describe the bug

**Command Name**
`az iot hub device-identity list
Extension Name: azure-iot. Version: 0.10.7.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'IotHubResourceOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\DavidJones\.azure\cliextensions\azure-iot\azext_iot\operations\hub.py", line 112, in iot_device_list
    result = iot_query(cmd, query, hub_name, top, resource_group_name, login=login)
  File "C:\Users\DavidJones\.azure\cliextensions\azure-iot\azext_iot\operations\hub.py", line 57, in iot_query
    target = discovery.get_target(
  File "C:\Users\DavidJones\.azure\cliextensions\azure-iot\azext_iot\iothub\providers\discovery.py", line 136, in get_target
    target_iothub = self.find_iothub(hub_name=hub_name, rg=rg)
  File "C:\Users\DavidJones\.azure\cliextensions\azure-iot\azext_iot\iothub\providers\discovery.py", line 72, in find_iothub
    self._initialize_client()
  File "C:\Users\DavidJones\.azure\cliextensions\azure-iot\azext_iot\iothub\providers\discovery.py", line 35, in _initialize_client
    self.sub_id = self.client.config.subscription_id
AttributeError: 'IotHubResourceOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub device-identity list -n $HubName   where $HubName is an existing hub , in env variable.

## Expected Behavior
Get a list of devices (which in this case is empty).

## Environment Summary
PS C:\Users\DavidJones\source\repos\az-iothub-ps\PS> write-host $HubName                        

HubPnP2

Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.2

Extensions:
azure-iot 0.10.7

```
## Additional Context

<!--Please don't remove this:-->
<!--auto-generated-->

**Comment by djaus2** [comment]
Yes that fixed it thx.
