### ISSUE TITLE
Extension Name: azure-iot. Version: 0.10.16.'az iot hub device-identity list' fails

### ISSUE THREAD

**Issue by franpb90** [Azure/azure-iot-cli-extension#431]
## Describe the bug

**Command Name**
`az iot hub device-identity list
Extension Name: azure-iot. Version: 0.10.16.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ItemPaged' object has no attribute 'advance_page'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\user1\.azure\cliextensions\azure-iot\azext_iot\operations\hub.py", line 131, in iot_device_list
    result = iot_query(
  File "C:\Users\user1\.azure\cliextensions\azure-iot\azext_iot\operations\hub.py", line 64, in iot_query
    target = discovery.get_target(
  File "C:\Users\user1\.azure\cliextensions\azure-iot\azext_iot\iothub\providers\discovery.py", line 173, in get_target
    target_policy = self.find_policy(
  File "C:\Users\user1\.azure\cliextensions\azure-iot\azext_iot\iothub\providers\discovery.py", line 120, in find_policy
    policy_list = self.get_policies(hub_name=hub_name, rg=rg)
  File "C:\Users\user1\.azure\cliextensions\azure-iot\azext_iot\iothub\providers\discovery.py", line 78, in get_policies
    policy_list.extend(policy_pager.advance_page())
AttributeError: 'ItemPaged' object has no attribute 'advance_page'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub device-identity list -n {} -g {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0

Extensions:
account 0.2.1
azure-devops 0.20.0
azure-iot 0.10.16
resource-graph 2.1.0
subscription 0.1.4
timeseriesinsights 0.2.1

```

**Comment by digimaun** [comment]
@franpb90  Thank you for bringing this to our attention, we are investigating.

For now can you try running the command after installing the last release `az extension add --name azure-iot --version 0.10.15`?

**Comment by franpb90** [comment]
Thank you @digimaun `az extension add --name azure-iot --version 0.10.15` is working as a temporal solution.

**Comment by digimaun** [comment]
You should be able to use latest (currently `0.10.17`) without issue now.

If you run into anymore problems, let us know.
