### ISSUE TITLE
Unexpected error is occurred by keyboard interrupting

### ISSUE THREAD

**Issue by aYukiYoshida** [Azure/azure-iot-cli-extension#450]
## Describe the bug

**Command Name**
`az iot hub monitor-events
Extension Name: azure-iot. Version: 0.10.13.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
type object '_asyncio.Task' has no attribute 'all_tasks'
Traceback (most recent call last):
  File "/Users/yyoshida/.azure/cliextensions/azure-iot/azext_iot/monitor/telemetry.py", line 74, in start_multiple_monitors
    result = loop.run_until_complete(future)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/yyoshida/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2756, in iot_hub_monitor_events
    _iot_hub_monitor_events(
  File "/Users/yyoshida/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2897, in _iot_hub_monitor_events
    start_single_monitor(
  File "/Users/yyoshida/.azure/cliextensions/azure-iot/azext_iot/monitor/telemetry.py", line 34, in start_single_monitor
    return start_multiple_monitors(
  File "/Users/yyoshida/.azure/cliextensions/azure-iot/azext_iot/monitor/telemetry.py", line 77, in start_multiple_monitors
    for t in asyncio.Task.all_tasks():  # pylint: disable=no-member
AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub monitor-events --hub-name {} --properties {} {} -d {}`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit, Darwin 19.6.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.29.1

Extensions:
azure-iot 0.10.13

```

**Comment by digimaun** [comment]
Closing this issue as we have not heard back from you. Please try the recommendation to update and if you are still running into the problem, then comment here and we can re-open the issue.
