### ISSUE TITLE
[bug] Cannot run on macOS due to incompatibilities with the Python version shipped with the Azure CLI

### ISSUE THREAD

**Issue by jimbobbennett** [Azure/azure-iot-cli-extension#469]
**Describe the bug**

When running macOS, you get the following error:

```output
The command failed with an unexpected error. Here is the traceback:
gather() got an unexpected keyword argument 'loop'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/jim/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2942, in iot_hub_monitor_events
    _iot_hub_monitor_events(
  File "/Users/jim/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 3083, in _iot_hub_monitor_events
    start_single_monitor(
  File "/Users/jim/.azure/cliextensions/azure-iot/azext_iot/monitor/telemetry.py", line 34, in start_single_monitor
    return start_multiple_monitors(
  File "/Users/jim/.azure/cliextensions/azure-iot/azext_iot/monitor/telemetry.py", line 69, in start_multiple_monitors
    future = asyncio.gather(*coroutines, loop=loop, return_exceptions=True)
TypeError: gather() got an unexpected keyword argument 'loop'
```

The Azure CLI ships Python 3.10 inside the packages, so you cannot avoid using this version.

**To Reproduce**

1. Try to use the extension on macOS

**Expected behavior**

It should work!

**Screenshots**

**Environment (please complete the following information):**

- OS: macOS 12.1.0
- Shell: zsh
- Az CLI version: 2.30.0
- IoT extension version: 0.11.0
- Python version (if pip installed): 3.10

**Additional context**

Looks like the code uses the `loop` parameter on `asyncio.gather`, which was deprecated in Python 3.8 and removed in Python 3.10:

https://githubmemory.com/repo/aio-libs/aiohttp/issues/5996

**Comment by marty-optum** [comment]
I can confirm the same error on an Intel Mac.  Here are some details on my Environment:

OS: macOS 11.6
Shell: bash
Az CLI version: 2.30.0
IoT extension version: 0.11.0
Python version (seems to be inherited from **homebrew**/azure-iot): 3.10

**Comment by jimbobbennett** [comment]
Looks like the `loop` parameter is no longer needed from Python 3.7 onwards. 

Options for a fix:

* Add an exception handler for the `TypeError` and if one is thrown, call the function without the `loop` parameter
* Remove the `loop` parameter and bump the minimum Python version to 3.7

**Comment by digimaun** [comment]
We have a new soft release of the `azure-iot` CLI extension `0.12.1` which should include `monitor-events` support for Python 3.10. That can be installed with `az extension add --source https://github.com/Azure/azure-iot-cli-extension/releases/download/v0.12.1/azure_iot-0.12.1-py3-none-any.whl` until its published to the extension index (to enable `az extension add --name azure-iot`). 

This should cover the macOS environment @marty-optum posted on an Intel Mac. Note there is a [known issue](https://github.com/Azure/azure-iot-cli-extension/issues/475) observed for keyboard interrupt on Py 3.10.

For apple silicon support ideally `uamqp` would provide a binary distribution for ARM architecture which you have already tracked down the repo and requested (thank you @jimbobbennett ).

In the meantime, as a workaround cloudshell can always be used to leverage the IoT CLI.

**Comment by marty-optum** [comment]
**Update**: I can confirm that the soft release of the `azure-iot` CLI extension [0.12.1](https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.12.1) fixed the error I previously experienced on an Intel Mac for my test use case.
 
Thank you.

**Comment by jimbobbennett** [comment]
Just testing this out, and it seems to be working with the latest release. Closing this issue.
