### ISSUE TITLE
CLI tool broken - Cannot monitor events

### ISSUE THREAD

**Issue by tfindlay-au** [Azure/azure-iot-cli-extension#491]
## Describe the bug

**Command Name**
`az iot hub monitor-events
Extension Name: azure-iot. Version: 0.11.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
gather() got an unexpected keyword argument 'loop'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/tfindlay/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2942, in iot_hub_monitor_events
    _iot_hub_monitor_events(
  File "/Users/tfindlay/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 3083, in _iot_hub_monitor_events
    start_single_monitor(
  File "/Users/tfindlay/.azure/cliextensions/azure-iot/azext_iot/monitor/telemetry.py", line 34, in start_single_monitor
    return start_multiple_monitors(
  File "/Users/tfindlay/.azure/cliextensions/azure-iot/azext_iot/monitor/telemetry.py", line 69, in start_multiple_monitors
    future = asyncio.gather(*coroutines, loop=loop, return_exceptions=True)
TypeError: gather() got an unexpected keyword argument 'loop'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub monitor-events -n {}`

## Environment Summary
```
macOS-12.2-x86_64-i386-64bit, Darwin 21.3.0
Python 3.10.1
Installer: HOMEBREW

azure-cli 2.31.0 *

Extensions:
azure-iot 0.11.0

```

**Comment by digimaun** [comment]
This is a known issue in 0.11.0. Updating to at least `0.12.1`  should fix the issue. You should be able to update with   `az extension update --name azure-iot`

Closing the issue for now. If after trying the above you still run into issues you can comment here and we can re-open.
