### ISSUE TITLE
Shell script fails when running `az iot hub device-identity list` on my iot hub

### ISSUE THREAD

**Issue by SimonSimCity** [Azure/azure-iot-cli-extension#502]
## Describe the bug

**Command Name**
`az iot hub device-identity list`
Extension Name: azure-iot. Version: 0.10.3.

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'IotHubResourceOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/simon/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 111, in iot_device_list
    result = iot_query(cmd, query, hub_name, top, resource_group_name, login=login)
  File "/Users/simon/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 56, in iot_query
    target = discovery.get_target(
  File "/Users/simon/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 136, in get_target
    target_iothub = self.find_iothub(hub_name=hub_name, rg=rg)
  File "/Users/simon/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 72, in find_iothub
    self._initialize_client()
  File "/Users/simon/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 35, in _initialize_client
    self.sub_id = self.client.config.subscription_id
AttributeError: 'IotHubResourceOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub device-identity list -n {}`

## Environment Summary
```
macOS-12.0.1-x86_64-i386-64bit, Darwin 21.1.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.34.1

Extensions:
azure-iot 0.10.3
timeseriesinsights 0.2.1
account 0.2.1

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by SimonSimCity** [comment]
Fixed it, thanks!
