### ISSUE TITLE
monitor events failing

### ISSUE THREAD

**Issue by roboenator** [Azure/azure-iot-cli-extension#521]
## Describe the bug
az iot hub monitor-events --output table --hub-name <redacted>
causes strange python error

**Command Name**
`az iot hub monitor-events
Extension Name: azure-iot. Version: 0.14.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'c_uamqp' from partially initialized module 'uamqp' (most likely due to a circular import) (/home/eric/.azure/cliextensions/azure-iot/uamqp/__init__.py)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/eric/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2958, in iot_hub_monitor_events
    _iot_hub_monitor_events(
  File "/home/eric/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 3071, in _iot_hub_monitor_events
    from azext_iot.monitor.builders import hub_target_builder
  File "/home/eric/.azure/cliextensions/azure-iot/azext_iot/monitor/builders/hub_target_builder.py", line 8, in <module>
    import uamqp
  File "/home/eric/.azure/cliextensions/azure-iot/uamqp/__init__.py", line 12, in <module>
    from uamqp import c_uamqp  # pylint: disable=import-self
ImportError: cannot import name 'c_uamqp' from partially initialized module 'uamqp' (most likely due to a circular import) (/home/eric/.azure/cliextensions/azure-iot/uamqp/__init__.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub monitor-events --output {} --hub-name {}`

## Environment Summary
```
Linux-5.4.0-1080-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
azure-iot 0.14.0
storage-preview 0.8.2
ai-examples 0.2.5
ssh 1.1.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by digimaun** [comment]
Hi @roboenator , if you recently updated your azure cli, try repairing the uamqp installation by executing the monitor-events command with `--repair` appended. Another option is to re-install the azure-iot extension. There are similar issues posted where this solution worked for them https://github.com/Azure/azure-iot-cli-extension/issues/499#issuecomment-1063210140.

**Comment by roboenator** [comment]
Hi @digimaun. That fixed it. Thank you so much for the help! I'm new at this azure stuff and still learning.  Thanks again!
