### ISSUE TITLE
Random IotHubNotFound error when executing commands

### ISSUE THREAD

**Issue by blackchoey** [Azure/azure-iot-cli-extension#77]
Hi, I'm getting following IotHubNotFound error when executing azure cli iot related commands: `ERROR: {'Message': 'ErrorCode:IotHubNotFound;Unauthorized', 'ExceptionMessage': 'Tracking ID:34b7ab68f5ca4cd1a0619419b705efe6-G:6-TimeStamp:06/19/2019 11:08:45'}`
I'm using Azure Pipelines Azure CLI task to run a series of Azure CLI commands. This error happened randomly and all previous operations against same iot hub succeeded. Any one can help take a look on the error?

**Comment by c-ryan-k** [comment]
@blackchoey - is this issue still occurring, or was it intermittent?

Also, could you share which commands you were running against your hub?

**Comment by blackchoey** [comment]
@c-ryan-k it happens randomly. The error I shared was from command `az iot hub device-identity show-connection-string`. Before this command I executed `az iot hub device-identity create --hub-name ... --device-id ... --edge-enabled --output none` and `az iot hub device-twin update --device-id ... --hub-name ... --set tags='{"environment":"dev"}'`.
I remembers the `az iot hub device-twin update` command also failed with same error before.

**Comment by digimaun** [comment]
Closing due to lack of activity. Please re-open if this keeps happening.

**Comment by weisssean** [comment]
@blackchoey blackchoey, did you ever find the answer to what was causing this?

**Comment by digimaun** [comment]
@weisssean @blackchoey - There is a good chance this error is caused by syncing delays of the resource provider with a freshly created hub. The best practice is to wait for 2 minutes after IoT Hub creation, to start interacting with the data plane services of the hub (such as creating devices).

If you get this error after waiting for the syncing delay please let me know.

**Comment by weisssean** [comment]
Thanks @digimaun, The hub is not new. I am successfully updating a device twin but every now and then, it throws this error.

**Comment by in-fke** [comment]
Also getting intermittent errors such as
```
2025-05-07T12:14:44,562 ERROR [global.azure-devices-provisioning.net-edbc8d7d-Cxnedbc8d7d-azure-iot-sdk-ProvisioningTask] common.AbstractDataSourceAdapterContext:402 adapter: AzureIoTHubDeviceClientAdapterTest Instance@local.sooTest (unknown): deviceId=soo-fnke, pdcrr.status=PROVISIONING_DEVICE_STATUS_FAILED
com.microsoft.azure.sdk.iot.provisioning.device.internal.exceptions.ProvisioningDeviceHubException: {"Message":"ErrorCode:IotHubNotFound;401","ExceptionMessage":"Tracking ID:CFC06A54306E4144B6527C9BF57F4234-G2:-TimeStamp:2025-05-07T10:14:42.199874637Z"}
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.ProvisioningTask.executeStateMachineForStatus(ProvisioningTask.java:247) [provisioning-device-client-2.1.3.jar:?]
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.ProvisioningTask.call(ProvisioningTask.java:343) [provisioning-device-client-2.1.3.jar:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
```

Using iot-device-client 2.5.0 and provisioning-device-client 2.1.3
